allowBuilds:
  "-": true
  "[": true
  "]": true
  a: true
  c: true
  e: true
  f: true
  ffmpeg-static: true
  g: true
  i: true
  m: true
  p: true
  s: true
  t: true
overrides:
  demo-reel: link:../../.local/share/pnpm/global/5/node_modules/demo-reel
