import { writeFile, mkdir } from "fs/promises";
import { dirname, relative, resolve } from "path";
import type { TimedScript } from "./types.js";
import type { Step } from "../schemas.js";

/**
 * Serialize a step to TypeScript source code.
 */
function serializeStep(step: Step, indent: string): string {
	const parts: string[] = [];

	// Action
	parts.push(`action: "${step.action}"`);

	// Action-specific fields
	if (step.action === "goto") {
		parts.push(`url: "${step.url}"`);
		if (step.waitUntil) parts.push(`waitUntil: "${step.waitUntil}"`);
	} else if (step.action === "wait") {
		parts.push(`ms: ${step.ms}`);
	} else if (step.action === "waitFor") {
		parts.push(`kind: "${step.kind}"`);
		if (step.kind === "selector") {
			parts.push(`selector: ${JSON.stringify(step.selector)}`);
			if (step.state) parts.push(`state: "${step.state}"`);
		} else if (step.kind === "url") {
			parts.push(`url: "${step.url}"`);
		} else if (step.kind === "loadState") {
			if (step.state) parts.push(`state: "${step.state}"`);
		} else if (step.kind === "request" || step.kind === "response") {
			parts.push(`url: "${step.url}"`);
		} else if (step.kind === "function") {
			parts.push(`expression: ${JSON.stringify(step.expression)}`);
		}
		if ("timeoutMs" in step && step.timeoutMs !== undefined) {
			parts.push(`timeoutMs: ${step.timeoutMs}`);
		}
	} else {
		// Steps with selector
		if ("selector" in step) {
			parts.push(`selector: ${JSON.stringify(step.selector)}`);
		}

		if (step.action === "type") {
			parts.push(`text: ${JSON.stringify(step.text)}`);
			if (step.clear) parts.push(`clear: true`);
			if (step.delayMs !== undefined) parts.push(`delayMs: ${step.delayMs}`);
		} else if (step.action === "press") {
			parts.push(`key: "${step.key}"`);
		} else if (step.action === "scroll") {
			parts.push(`x: ${step.x}, y: ${step.y}`);
		} else if (step.action === "select") {
			parts.push(`value: ${JSON.stringify(step.value)}`);
		} else if (step.action === "check") {
			parts.push(`checked: ${step.checked}`);
		} else if (step.action === "upload") {
			parts.push(`filePath: ${JSON.stringify(step.filePath)}`);
		} else if (step.action === "drag") {
			parts.push(`source: ${JSON.stringify(step.source)}`);
			parts.push(`target: ${JSON.stringify(step.target)}`);
		}
	}

	// Delay fields (present on most step types)
	if ("delayBeforeMs" in step && step.delayBeforeMs !== undefined && step.delayBeforeMs > 0) {
		parts.push(`delayBeforeMs: ${step.delayBeforeMs}`);
	}
	if ("delayAfterMs" in step && step.delayAfterMs !== undefined && step.delayAfterMs > 0) {
		parts.push(`delayAfterMs: ${step.delayAfterMs}`);
	}

	return `${indent}{ ${parts.join(", ")} }`;
}

/**
 * Generate a complete .demo.ts file from a timed script.
 */
export function generateDemoConfig(
	script: TimedScript,
	options: {
		resolution?: string;
		format?: string;
		outputDir?: string;
	} = {},
): string {
	const resolution = options.resolution || "FHD";
	const format = options.format || "mp4";

	// Collect all steps from all scenes, with scene comments
	const stepLines: string[] = [];

	for (let i = 0; i < script.scenes.length; i++) {
		const scene = script.scenes[i];
		const narrationPreview = scene.narration.slice(0, 80);

		stepLines.push(`    // Scene ${i + 1}: "${narrationPreview}${scene.narration.length > 80 ? "..." : ""}"`);

		for (const step of scene.steps) {
			stepLines.push(`${serializeStep(step as Step, "    ")},`);
		}

		// Add gap between scenes (except last)
		if (i < script.scenes.length - 1 && scene.gapAfterMs > 0) {
			stepLines.push(`    { action: "wait", ms: ${scene.gapAfterMs} },`);
		}

		stepLines.push("");
	}

	const configSource = `// Generated by demo-reel script
// ${script.title}
import { defineConfig } from "demo-reel";

export default defineConfig({
  video: {
    resolution: "${resolution}",
  },

  cursor: "dot",
  motion: "smooth",
  typing: "humanlike",
  timing: "normal",
  outputFormat: "${format}",

  audio: {
    narration: "${script.audioPath}",
    narrationDelay: 300,
  },

  steps: [
${stepLines.join("\n")}  ],
});
`;

	return configSource;
}

/**
 * Write the generated .demo.ts file to disk.
 */
export async function writeDemoConfig(
	script: TimedScript,
	outputPath: string,
	options: {
		resolution?: string;
		format?: string;
	} = {},
): Promise<void> {
	await mkdir(dirname(outputPath), { recursive: true });

	// Make audio path relative to the output config file
	const configDir = dirname(resolve(outputPath));
	const relativeAudioPath = relative(configDir, resolve(script.audioPath));

	const scriptWithRelativePath: TimedScript = {
		...script,
		audioPath: relativeAudioPath.startsWith(".") ? relativeAudioPath : `./${relativeAudioPath}`,
	};

	const source = generateDemoConfig(scriptWithRelativePath, options);
	await writeFile(outputPath, source, "utf-8");
}

/**
 * Write the script JSON file for later editing/re-processing.
 */
export async function writeScriptJson(
	script: TimedScript | { title: string; description: string; url: string; scenes: unknown[] },
	outputPath: string,
): Promise<void> {
	await mkdir(dirname(outputPath), { recursive: true });
	await writeFile(outputPath, JSON.stringify(script, null, 2), "utf-8");
}
