export {
  demoReelConfigSchema,
  demoReelConfigInputSchema,
  demoReelVideoOnlySchema,
  type DemoReelConfig,
  type DemoReelConfigInput,
} from "./schemas/root.js";

export {
  sizeSchema,
  resolutionPresetSchema,
  resolutionSchema,
  selectorStrategySchema,
  selectorSchema,
  stepSchema,
  storageTypeSchema,
  authStorageConfigSchema,
  authValidateConfigSchema,
  authBehaviorConfigSchema,
  authConfigSchema,
  runtimeSceneSchema,
  type SizeConfig,
  type ResolutionPreset,
  type ResolutionConfig,
  type SelectorStrategy,
  type SelectorConfig,
  type Step,
  type StorageType,
  type AuthStorageConfig,
  type AuthValidateConfig,
  type AuthBehaviorConfig,
  type AuthConfig,
  type RandomizationConfig,
  type RuntimeScene,
} from "./schemas/shared.js";

export {
  cursorPresetSchema,
  motionPresetSchema,
  typingPresetSchema,
  timingPresetSchema,
  cursorSchema,
  motionSchema,
  timingSchema,
  narrationSyncModeSchema,
  typingSchema,
  videoConfigSchema,
  outputFormatSchema,
  audioConfigSchema,
  videoConfigInputSchema,
  demoReelVideoConfigSchema,
  type DemoReelVideoConfig,
  type DemoReelVideoConfigInput,
  type CursorPresetOrConfig,
  type MotionPresetOrConfig,
  type TypingPresetOrConfig,
  type TimingPresetOrConfig,
  type CursorConfig,
  type MotionConfig,
  type TimingConfig,
  type TypingConfig,
  type VideoConfig,
  type AudioConfig,
  type NarrationSyncMode,
} from "./schemas/video.js";

export {
  e2eConfigInputSchema,
  type DemoReelE2EConfig,
  type DemoReelE2EConfigInput,
  type E2ECheckpoint,
  type E2EAssertion,
} from "./schemas/e2e.js";
