export type {
  CursorConfig,
  MotionConfig,
  TimingConfig,
  TypingConfig,
  VideoConfig,
  AudioConfig,
  StorageType,
  AuthStorageConfig,
  AuthValidateConfig,
  AuthBehaviorConfig,
  AuthConfig,
  SelectorStrategy,
  SelectorConfig,
  Step,
  NarrationSyncMode,
  DemoReelConfig,
  DemoReelConfigInput,
  CursorPresetOrConfig,
  MotionPresetOrConfig,
  TypingPresetOrConfig,
  TimingPresetOrConfig,
  ResolutionPreset,
  ResolutionConfig,
  RandomizationConfig,
} from "./schemas.js";
