export type {
  SizeConfig,
  CursorConfig,
  MotionConfig,
  TimingConfig,
  TypingConfig,
  VideoConfig,
  AudioConfig,
  StorageType,
  AuthStorageConfig,
  AuthValidateConfig,
  AuthBehaviorConfig,
  AuthConfig,
  SelectorStrategy,
  SelectorConfig,
  Step,
  DemoReelConfig,
} from './schemas.js';
